Repository Sandbox-gVisor/Sandbox, pull requests merged in 2023-07, with the labels that each got.

#41 40 callbacks configuration in runtime
  pkg/sentry/kernel/BUILD
  pkg/sentry/kernel/callback_table.go
  pkg/sentry/kernel/callbacks/callback_config.go
  pkg/sentry/kernel/kernel.go
  pkg/sentry/kernel/runtime_cmd.go
  runsc/boot/loader.go
  runsc/cmd/boot.go
  runsc/sandbox/BUILD
  runsc/sandbox/sandbox.go
Labels: enhancement

#54 49 fix callbacks
  pkg/sentry/kernel/BUILD
  pkg/sentry/kernel/callback_table.go
  pkg/sentry/kernel/callbacks.go
  pkg/sentry/kernel/callbacks/callback_config.go
  pkg/sentry/kernel/callbacks/util.go
  pkg/sentry/kernel/hooks.go
  pkg/sentry/kernel/kernel.go
  pkg/sentry/kernel/runtime_cmd.go
  pkg/sentry/kernel/task_syscall.go
Labels: enhancement, refactor

#63 59 implements change state and hooks info commands in gvisor
  pkg/sentry/kernel/callbacks.go
  pkg/sentry/kernel/callbacks/callback_config.go
  pkg/sentry/kernel/runtime_cmd.go
Labels: enhancement

#68 fix of commands
  pkg/sentry/kernel/callbacks.go
  pkg/sentry/kernel/runtime_cmd.go
Labels: bug

#71 fixes
  pkg/abi/linux/file.go
  pkg/sentry/kernel/hooks.go
  pkg/sentry/strace/open.go
Labels: enhancement

#85 74 refactor of commands in gvisor
  pkg/sentry/kernel/kernel.go
  pkg/sentry/kernel/runtime_cmd.go
Labels: refactor

#91 Create gvisor_api.yml
  gvisor_api.yml
Labels: documentation

#92 39 add global context objects for each task and kernel
  pkg/sentry/kernel/callbacks.go
  pkg/sentry/kernel/callbacks/BUILD
  pkg/sentry/kernel/callbacks/callback_config.go
  pkg/sentry/kernel/callbacks/util.go
  pkg/sentry/kernel/hooks.go
  pkg/sentry/kernel/kernel.go
  pkg/sentry/kernel/runtime_cmd.go
  pkg/sentry/kernel/task_work.go
  runsc/cli/main.go
Labels: enhancement

#94 93 callback registration from js
  pkg/sentry/kernel/callbacks.go
  pkg/sentry/kernel/callbacks/util.go
  pkg/sentry/kernel/hooks.go
  pkg/sentry/kernel/kernel.go
  pkg/sentry/kernel/runtime_cmd.go
  pkg/sentry/kernel/task_syscall.go
Labels: enhancement

#95 fix after fixes
  README.md
  init_script.sh
  pkg/sentry/kernel/runtime_cmd.go
Labels: bug
